CFLAGS=-O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow
LIBS=-lm
EXECUTAVEL=Lista

all: $(EXECUTAVEL)

$(EXECUTAVEL): lista.o
	gcc lista.o $(LIBS) -o $(EXECUTAVEL)


lista.o: lista.c
	gcc $(CFLAGS) -c lista.c

clean:
	rm -rf *.o $(EXECUTAVEL)

memcheck: $(EXECUTAVEL)
	valgrind --tool=memcheck --leak-check=full ./$(EXECUTAVEL)

run: $(EXECUTAVEL)
	./$(EXECUTAVEL)